"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, Grid3X3, List, Pencil, Search, X } from "lucide-react";
import { PaymentEditForm, PaymentForm } from "@/components/forms/collection-forms";
import { formatMoney } from "@/lib/utils";

export type CollectionRow = {
  id: string; projectServiceId: string; month: number; client: string; project: string; service: string;
  billing: "invoiced" | "uninvoiced"; total: number; paid: number; currency: string; dueDate: string | null;
  status: string; payments: { id: string; amount: number; paymentDate: string; accountId: string | null; accountName: string | null; notes: string | null }[];
};
type Account = { id: string; name: string; currency: string };
const months = ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"];

export function CollectionWorkspace({ rows, accounts, year }: { rows: CollectionRow[]; accounts: Account[]; year: number }) {
  const router = useRouter();
  const [query, setQuery] = useState("");
  const [service, setService] = useState("");
  const [billing, setBilling] = useState("");
  const [view, setView] = useState<"matrix" | "list">("matrix");
  const [selected, setSelected] = useState<CollectionRow | null>(null);
  const services = [...new Set(rows.map((row) => row.service))].sort((a, b) => a.localeCompare(b, "tr"));
  const filtered = rows.filter((row) => (!query || `${row.client} ${row.project}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))) && (!service || row.service === service) && (!billing || row.billing === billing));
  const summary = useMemo(() => filtered.filter((row) => row.currency === "TRY").reduce((value, row) => ({ expected: value.expected + row.total, paid: value.paid + row.paid, overdue: value.overdue + (isOverdue(row) ? row.total - row.paid : 0) }), { expected: 0, paid: 0, overdue: 0 }), [filtered]);
  const groups = useMemo(() => {
    const map = new Map<string, { client: string; project: string; service: string; billing: CollectionRow["billing"]; months: Map<number, CollectionRow> }>();
    filtered.forEach((row) => { const current = map.get(row.projectServiceId) || { client: row.client, project: row.project, service: row.service, billing: row.billing, months: new Map() }; current.months.set(row.month, row); map.set(row.projectServiceId, current); });
    return [...map.values()];
  }, [filtered]);

  return <>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Summary label="Beklenen tahsilat" value={formatMoney(summary.expected, "TRY")} />
      <Summary label="Tahsil edilen" value={formatMoney(summary.paid, "TRY")} positive />
      <Summary label="Kalan tahsilat" value={formatMoney(Math.max(0, summary.expected - summary.paid), "TRY")} />
      <Summary label="Geciken alacak" value={formatMoney(summary.overdue, "TRY")} danger />
    </div>
    <div className="mb-5 flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
      <label className="min-w-60 flex-1 text-xs font-medium text-slate-500"><span className="mb-1.5 block">Müşteri veya proje ara</span><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={16}/><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm" placeholder="Müşteri, proje veya domain"/></div></label>
      <Filter label="Hizmet" value={service} onChange={setService}><option value="">Tüm hizmetler</option>{services.map((name) => <option key={name}>{name}</option>)}</Filter>
      <Filter label="Faturalama" value={billing} onChange={setBilling}><option value="">Tümü</option><option value="invoiced">Faturalı</option><option value="uninvoiced">Faturasız</option></Filter>
      <div className="flex h-10 rounded-lg bg-slate-100 p-1"><button onClick={() => setView("matrix")} title="Matris görünümü" className={`rounded-md px-3 ${view === "matrix" ? "bg-white text-[#CD0B16] shadow-sm" : "text-slate-500"}`}><Grid3X3 size={17}/></button><button onClick={() => setView("list")} title="Liste görünümü" className={`rounded-md px-3 ${view === "list" ? "bg-white text-[#CD0B16] shadow-sm" : "text-slate-500"}`}><List size={17}/></button></div>
    </div>
    {view === "matrix" ? <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="min-w-[2200px] text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-slate-500"><tr><th className="sticky left-0 z-20 min-w-72 border-b border-r bg-slate-50 px-4 py-3">Müşteri / Proje</th><th className="min-w-32 border-b px-3">Hizmet</th><th className="min-w-24 border-b px-3">Fatura</th>{months.map((month) => <th key={month} className="min-w-32 border-b border-l px-3 text-center">{month}</th>)}</tr></thead><tbody>{groups.map((group) => <tr key={`${group.project}-${group.service}`} className="border-b last:border-0"><td className="sticky left-0 z-10 border-r bg-white px-4 py-3"><div className="font-semibold text-slate-800">{group.project}</div><div className="mt-1 text-slate-400">{group.client}</div></td><td className="px-3 font-medium">{group.service}</td><td className="px-3"><span className={`rounded-full px-2 py-1 ${group.billing === "invoiced" ? "bg-emerald-50 text-emerald-700" : "bg-blue-50 text-blue-700"}`}>{group.billing === "invoiced" ? "Faturalı" : "Faturasız"}</span></td>{Array.from({ length: 12 }, (_, index) => { const row = group.months.get(index + 1); return <td key={index} className="border-l p-1.5">{row ? <MonthCell row={row} onClick={() => setSelected(row)} /> : <div className="h-16 rounded-lg bg-slate-50"/>}</td>; })}</tr>)}</tbody></table>{!groups.length && <div className="p-12 text-center text-sm text-slate-400">Seçilen filtrelerde tahsilat kaydı bulunamadı.</div>}</div> : <div className="overflow-hidden rounded-xl border bg-white"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs text-slate-500"><tr>{["Müşteri / Proje","Hizmet","Dönem","Beklenen","Tahsil edilen","Kalan","Vade","Durum"].map((x) => <th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map((row) => <tr key={row.id} onClick={() => setSelected(row)} className="cursor-pointer hover:bg-slate-50"><td className="px-4 py-3"><b>{row.project}</b><div className="text-xs text-slate-400">{row.client}</div></td><td className="px-4">{row.service}</td><td className="px-4">{months[row.month - 1]} {year}</td><td className="px-4">{formatMoney(row.total,row.currency)}</td><td className="px-4 text-emerald-700">{formatMoney(row.paid,row.currency)}</td><td className="px-4 font-medium">{formatMoney(row.total-row.paid,row.currency)}</td><td className="px-4">{row.dueDate||"—"}</td><td className="px-4"><Status row={row}/></td></tr>)}</tbody></table></div>}
    {selected && <PaymentModal row={selected} accounts={accounts.filter((account) => account.currency === selected.currency)} onClose={() => setSelected(null)} onSaved={() => { setSelected(null); router.refresh(); }}/>} 
  </>;
}

function MonthCell({ row, onClick }: { row: CollectionRow; onClick: () => void }) { const remaining = Math.max(0,row.total-row.paid); const tone = row.status === "paid" ? "bg-emerald-50 hover:bg-emerald-100" : row.status === "partial" ? "bg-amber-50 hover:bg-amber-100" : isOverdue(row) ? "bg-red-50 hover:bg-red-100" : "bg-slate-50 hover:bg-slate-100"; return <button onClick={onClick} className={`h-16 w-full rounded-lg p-2 text-left transition ${tone}`}><div className="font-bold text-slate-800">{row.paid ? formatMoney(row.paid,row.currency) : "Ödeme bekliyor"}</div><div className="mt-1 text-[10px] text-slate-500">Beklenen {formatMoney(row.total,row.currency)}</div>{remaining > 0 && row.paid > 0 && <div className="text-[10px] text-amber-700">Kalan {formatMoney(remaining,row.currency)}</div>}</button>; }
function Status({ row }: { row: CollectionRow }) { const label = row.status === "paid" ? "Ödendi" : row.status === "partial" ? "Kısmi" : isOverdue(row) ? "Gecikti" : "Bekleniyor"; return <span className={`rounded-full px-2 py-1 text-xs ${row.status === "paid" ? "bg-emerald-50 text-emerald-700" : row.status === "partial" ? "bg-amber-50 text-amber-700" : isOverdue(row) ? "bg-red-50 text-red-700" : "bg-slate-100 text-slate-600"}`}>{label}</span>; }
function isOverdue(row: CollectionRow) { return row.status !== "paid" && !!row.dueDate && row.dueDate < new Date().toISOString().slice(0,10); }
function Summary({ label, value, positive, danger }: { label: string; value: string; positive?: boolean; danger?: boolean }) { return <div className="rounded-xl border bg-white p-5 shadow-sm"><div className="text-sm text-slate-500">{label}</div><div className={`mt-2 text-xl font-bold ${positive ? "text-emerald-700" : danger ? "text-[#CD0B16]" : "text-slate-900"}`}>{value}</div></div>; }
function Filter({ label, value, onChange, children }: { label: string; value: string; onChange: (value:string)=>void; children: React.ReactNode }) { return <label className="min-w-44 text-xs font-medium text-slate-500"><span className="mb-1.5 block">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700">{children}</select></label>; }
function PaymentModal({ row, accounts, onClose, onSaved }: { row: CollectionRow; accounts: Account[]; onClose:()=>void; onSaved:()=>void }) {
  const remaining = Math.max(0, row.total - row.paid);
  const [editingPayment, setEditingPayment] = useState<CollectionRow["payments"][number] | null>(null);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose();}}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b p-5"><div><div className="text-xs text-slate-400">{months[row.month-1]} · {row.service}</div><h2 className="mt-1 text-xl font-bold">{row.project}</h2><p className="text-sm text-slate-500">{row.client}</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X size={20}/></button></header><div className="p-5"><div className="mb-5 grid grid-cols-3 gap-3"><Mini label="Beklenen" value={formatMoney(row.total,row.currency)}/><Mini label="Tahsil edilen" value={formatMoney(row.paid,row.currency)}/><Mini label="Kalan" value={formatMoney(remaining,row.currency)}/></div>{remaining>0?<><h3 className="mb-4 font-semibold">Ödeme kaydet</h3><PaymentForm receivableId={row.id} maxAmount={remaining} accounts={accounts} onSuccess={onSaved}/></>:<div className="rounded-lg bg-emerald-50 p-4 text-sm text-emerald-700">Bu dönem tamamen tahsil edildi.</div>}<div className="mt-6 border-t pt-5"><h3 className="mb-3 flex items-center gap-2 font-semibold"><CalendarDays size={16}/>Ödeme geçmişi</h3><div className="space-y-2">{row.payments.map((payment)=><div key={payment.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><div><b>{payment.paymentDate}</b><div className="text-xs text-slate-400">{payment.accountName||"Kasa belirtilmedi"}</div></div><div className="flex items-center gap-3"><b>{formatMoney(payment.amount,row.currency)}</b><button type="button" title="Ödemeyi düzenle" onClick={() => setEditingPayment(payment)} className="rounded-md border border-slate-200 bg-white p-2 text-slate-500 hover:border-red-200 hover:text-[#CD0B16]"><Pencil size={14}/></button></div></div>)}{!row.payments.length&&<div className="text-sm text-slate-400">Henüz ödeme girilmedi.</div>}</div></div>{editingPayment && <div className="mt-5 rounded-xl border border-red-100 bg-red-50/30 p-4"><h3 className="mb-4 font-semibold">Ödemeyi düzenle</h3><PaymentEditForm payment={editingPayment} maxAmount={remaining + editingPayment.amount} accounts={accounts} onSuccess={onSaved} onCancel={() => setEditingPayment(null)}/></div>}</div></div></div>;
}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><div className="text-xs text-slate-400">{label}</div><b className="mt-1 block">{value}</b></div>}
