"use server";
import{redirect}from"next/navigation";import{z}from"zod";import{createClient}from"@/lib/supabase/server";
const item=z.object({service_id:z.string().uuid().or(z.literal("")),custom_service_name:z.string().trim().optional(),description:z.string().min(1),quantity:z.coerce.number().positive(),unit_price:z.coerce.number().min(0),discount_rate:z.coerce.number().min(0).max(100),vat_rate:z.coerce.number().min(0).max(100)});const schema=z.object({client_id:z.string().optional(),lead_id:z.string().optional(),offer_date:z.string().date(),valid_until:z.string().optional(),sales_owner_id:z.string().optional(),currency:z.enum(["TRY","USD","EUR","GBP"]),description:z.string().optional(),payment_terms:z.string().optional(),notes:z.string().optional(),items:z.array(item).min(1)}).refine(x=>Boolean(x.client_id)!==Boolean(x.lead_id),"Müşteri veya lead seçin.");
export async function createOffer(payload:unknown){const p=schema.safeParse(payload);if(!p.success)return{error:p.error.issues[0]?.message||"Teklif bilgilerini kontrol edin."};const d=p.data;const s=await createClient();const{data,error}=await s.rpc("create_offer_with_revision",{p_client_id:d.client_id||null,p_lead_id:d.lead_id||null,p_offer_date:d.offer_date,p_valid_until:d.valid_until||null,p_sales_owner_id:d.sales_owner_id||null,p_currency:d.currency,p_description:d.description||null,p_payment_terms:d.payment_terms||null,p_notes:d.notes||null,p_items:d.items});if(error)return{error:error.message};redirect(`/offers/${data}`)}
const revisionSchema=z.object({offer_id:z.string().uuid(),description:z.string().optional(),payment_terms:z.string().optional(),notes:z.string().optional(),items:z.array(item).min(1)});
export async function createOfferRevision(payload:unknown){const p=revisionSchema.safeParse(payload);if(!p.success)return{error:p.error.issues[0]?.message||"Revizyon bilgilerini kontrol edin."};const d=p.data;const s=await createClient();const{error}=await s.rpc("create_offer_revision",{p_offer_id:d.offer_id,p_description:d.description||null,p_payment_terms:d.payment_terms||null,p_notes:d.notes||null,p_items:d.items});if(error)return{error:error.message};redirect(`/offers/${d.offer_id}`)}
export async function setOfferStatus(id:string,status:"draft"|"ready"|"sent"|"revising"|"accepted"|"rejected"|"expired"){const s=await createClient();const{error}=await s.from("offers").update({status}).eq("id",id);if(error)throw new Error(error.message)}
export async function createProformaFromOffer(_: {error?:string}|null,fd:FormData){const offerId=String(fd.get("offer_id")||"");const issueDate=String(fd.get("issue_date")||"");const validUntil=String(fd.get("valid_until")||"");const bankDetails=String(fd.get("bank_details")||"");if(!z.string().uuid().safeParse(offerId).success||!z.string().date().safeParse(issueDate).success)return{error:"Proforma bilgilerini kontrol edin."};const s=await createClient();const{data,error}=await s.rpc("create_proforma_from_offer",{p_offer_id:offerId,p_issue_date:issueDate,p_valid_until:validUntil||null,p_bank_details:bankDetails||null});if(error)return{error:error.message.includes("must_belong")?"Proforma için teklif bir müşteri kaydına bağlı olmalı.":error.message};redirect(`/proformas/${data}`)}
const conversionSchema=z.object({offer_id:z.string().uuid(),project_name:z.string().trim().min(2),domain:z.string().trim().optional(),start_date:z.string().date(),owner_id:z.union([z.literal(""),z.string().uuid()]).optional(),is_white_label:z.string().optional()});
export async function convertOfferToProject(_: {error?:string}|null,fd:FormData){const p=conversionSchema.safeParse(Object.fromEntries(fd));if(!p.success)return{error:"Proje bilgilerini kontrol edin."};const d=p.data;const s=await createClient();const{data,error}=await s.rpc("convert_offer_to_project",{p_offer_id:d.offer_id,p_project_name:d.project_name,p_domain:d.domain||null,p_start_date:d.start_date,p_owner_id:d.owner_id||null,p_is_white_label:d.is_white_label==="on"});if(error)return{error:error.message.includes("must_be_accepted")?"Önce teklif durumunu Kabul Edildi yapın.":error.message.includes("must_belong")?"Teklif bir müşteri kaydına bağlı olmalı.":error.message};redirect(`/projects/${data}`)}
