"use server";
import{revalidatePath}from"next/cache";import{z}from"zod";import{createClient}from"@/lib/supabase/server";
export type OperationState={error?:string;success?:string}|null;
const reportSchema=z.object({project_id:z.string().uuid(),project_service_id:z.union([z.literal(""),z.string().uuid()]).optional(),period:z.string().date(),title:z.string().trim().min(2),url:z.union([z.literal(""),z.string().url()]).optional(),status:z.enum(["planned","preparing","ready","sent","approved"]),notes:z.string().optional()});
export async function createReport(_:OperationState,fd:FormData):Promise<OperationState>{const p=reportSchema.safeParse(Object.fromEntries(fd));if(!p.success)return{error:p.error.issues[0]?.message||"Rapor bilgilerini kontrol edin."};const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return{error:"Oturum bulunamadı."};const{error}=await s.from("reports").insert({...p.data,project_service_id:p.data.project_service_id||null,url:p.data.url||null,notes:p.data.notes||null,prepared_by:user.id,created_by:user.id,sent_at:p.data.status==="sent"?new Date().toISOString():null});if(error)return{error:error.message};revalidatePath(`/projects/${p.data.project_id}/reports`);return{success:"Rapor kaydı oluşturuldu."}}
export async function setReportStatus(id:string,projectId:string,status:"planned"|"preparing"|"ready"|"sent"|"approved"){const s=await createClient();const{error}=await s.from("reports").update({status,sent_at:status==="sent"?new Date().toISOString():undefined}).eq("id",id);if(error)throw new Error(error.message);revalidatePath(`/projects/${projectId}/reports`)}
const recurringSchema=z.object({project_id:z.string().uuid(),project_service_id:z.union([z.literal(""),z.string().uuid()]).optional(),title:z.string().trim().min(2),description:z.string().optional(),priority:z.enum(["low","normal","high","urgent"]),recurrence:z.enum(["daily","weekly","monthly","custom"]),interval_value:z.coerce.number().int().min(1).max(365),starts_on:z.string().date(),ends_on:z.string().optional()});
export async function createRecurringTemplate(_:OperationState,fd:FormData):Promise<OperationState>{const p=recurringSchema.safeParse(Object.fromEntries(fd));if(!p.success)return{error:p.error.issues[0]?.message||"Şablon bilgilerini kontrol edin."};const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return{error:"Oturum bulunamadı."};const{error}=await s.from("recurring_task_templates").insert({...p.data,project_service_id:p.data.project_service_id||null,description:p.data.description||null,ends_on:p.data.ends_on||null,next_run_on:p.data.starts_on,created_by:user.id});if(error)return{error:error.message};revalidatePath(`/projects/${p.data.project_id}/recurring-tasks`);return{success:"Tekrarlayan görev şablonu oluşturuldu."}}
export async function setRecurringStatus(id:string,projectId:string,isActive:boolean){const s=await createClient();const{error}=await s.from("recurring_task_templates").update({is_active:isActive}).eq("id",id);if(error)throw new Error(error.message);revalidatePath(`/projects/${projectId}/recurring-tasks`)}
export async function generateRecurringTasks(projectId:string){const s=await createClient();const{data,error}=await s.rpc("generate_due_recurring_tasks",{p_project_id:projectId,p_run_date:new Date().toISOString().slice(0,10)});if(error)throw new Error(error.message);revalidatePath(`/projects/${projectId}/recurring-tasks`);revalidatePath(`/projects/${projectId}/tasks`);return Number(data||0)}
