"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

export type ActionState = { error?: string; success?: string } | null;
const serviceInput = z.object({ project_id:z.string().uuid(), service_id:z.string().uuid(), periodicity:z.enum(["monthly","one_time","periodic"]), currency:z.enum(["TRY","USD","EUR","GBP"]), billing_preference:z.enum(["invoiced","uninvoiced"]), start_date:z.string().date(), payment_term_days:z.coerce.number().int().min(0).max(365), net_price:z.coerce.number().min(0), vat_rate:z.coerce.number().min(0).max(100), notes:z.string().optional() });
export async function addProjectService(_:ActionState,fd:FormData):Promise<ActionState>{const parsed=serviceInput.safeParse(Object.fromEntries(fd));if(!parsed.success)return{error:parsed.error.issues[0]?.message||"Bilgileri kontrol edin."};const s=await createClient();const d=parsed.data;const{error}=await s.rpc("create_project_service_with_price",{p_project_id:d.project_id,p_service_id:d.service_id,p_periodicity:d.periodicity,p_currency:d.currency,p_billing_preference:d.billing_preference,p_start_date:d.start_date,p_payment_term_days:d.payment_term_days,p_notes:d.notes||null,p_net_price:d.net_price,p_vat_rate:d.vat_rate});if(error)return{error:error.code==="42501"?"Bu işlem için yetkiniz yok.":error.message};revalidatePath(`/projects/${d.project_id}`);return{success:"Proje hizmeti eklendi."}}

const memberInput=z.object({project_id:z.string().uuid(),profile_id:z.string().uuid(),access_level:z.enum(["viewer","member","manager"])});
export async function addProjectMember(_:ActionState,fd:FormData):Promise<ActionState>{const p=memberInput.safeParse(Object.fromEntries(fd));if(!p.success)return{error:"Ekip üyesini ve erişim seviyesini seçin."};const s=await createClient();const{error}=await s.from("project_members").upsert(p.data,{onConflict:"project_id,profile_id"});if(error)return{error:error.message};revalidatePath(`/projects/${p.data.project_id}`);return{success:"Ekip üyesi atandı."}}

const priceInput=z.object({project_id:z.string().uuid(),project_service_id:z.string().uuid(),net_price:z.coerce.number().min(0),vat_rate:z.coerce.number().min(0).max(100),currency:z.enum(["TRY","USD","EUR","GBP"]),effective_from:z.string().date()});
export async function changeProjectServicePrice(_:ActionState,fd:FormData):Promise<ActionState>{const p=priceInput.safeParse(Object.fromEntries(fd));if(!p.success)return{error:p.error.issues[0]?.message||"Fiyat bilgilerini kontrol edin."};const s=await createClient();const{project_id,...d}=p.data;const{error}=await s.rpc("change_project_service_price",{p_project_service_id:d.project_service_id,p_net_price:d.net_price,p_vat_rate:d.vat_rate,p_currency:d.currency,p_effective_from:d.effective_from});if(error)return{error:error.message.includes("new_price_date")?"Yeni fiyat tarihi mevcut fiyat başlangıcından sonra olmalı.":error.message};revalidatePath(`/projects/${project_id}`);return{success:"Yeni fiyat dönemi oluşturuldu."}}

const serviceMemberInput=z.object({project_id:z.string().uuid(),project_service_id:z.string().uuid(),profile_id:z.string().uuid()});
export async function addProjectServiceMember(_:ActionState,fd:FormData):Promise<ActionState>{const p=serviceMemberInput.safeParse(Object.fromEntries(fd));if(!p.success)return{error:"Ekip üyesini seçin."};const s=await createClient();const{project_id,...row}=p.data;const{error}=await s.from("project_service_members").upsert(row,{onConflict:"project_service_id,profile_id"});if(error)return{error:error.message};revalidatePath(`/projects/${project_id}`);return{success:"Hizmet ekibi güncellendi."}}
