"use server";
import{revalidatePath}from"next/cache";import{z}from"zod";import{createClient}from"@/lib/supabase/server";
export type SalesState={error?:string;success?:string}|null;
const leadSchema=z.object({company_name:z.string().trim().min(2),contact_name:z.string().optional(),phone:z.string().optional(),email:z.union([z.literal(""),z.string().email()]).optional(),source:z.string().optional(),estimated_budget:z.union([z.literal(""),z.coerce.number().min(0)]).optional(),currency:z.enum(["TRY","USD","EUR","GBP"]),sales_owner_id:z.union([z.literal(""),z.string().uuid()]).optional(),next_contact_date:z.string().optional(),description:z.string().optional()});
export async function createLead(_:SalesState,fd:FormData):Promise<SalesState>{const p=leadSchema.safeParse(Object.fromEntries(fd));if(!p.success)return{error:p.error.issues[0]?.message||"Lead bilgilerini kontrol edin."};const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return{error:"Oturum bulunamadı."};const{data:lead,error}=await s.from("leads").insert({...p.data,email:p.data.email||null,estimated_budget:p.data.estimated_budget||null,sales_owner_id:p.data.sales_owner_id||null,next_contact_date:p.data.next_contact_date||null,created_by:user.id,updated_by:user.id}).select("id").single();if(error)return{error:error.message};const services=fd.getAll("services").map(String);if(services.length)await s.from("lead_services").insert(services.map(service_id=>({lead_id:lead.id,service_id})));revalidatePath("/sales");return{success:"Lead oluşturuldu."}}
export async function moveLead(leadId:string,status:"new"|"contacted"|"meeting"|"preparing_offer"|"offer_sent"|"negotiation"|"won"|"lost"){const s=await createClient();const{data:{user}}=await s.auth.getUser();const{error}=await s.from("leads").update({status,updated_by:user?.id}).eq("id",leadId);if(error)throw new Error(error.message);if(user)await s.from("lead_activities").insert({lead_id:leadId,activity_type:"status_change",note:`Durum ${status} olarak değiştirildi.`,created_by:user.id});revalidatePath("/sales")}
const activitySchema=z.object({lead_id:z.string().uuid(),activity_type:z.enum(["call","whatsapp","email","meeting","note","status_change"]),note:z.string().trim().min(1).max(5000)});
export async function addLeadActivity(_:SalesState,fd:FormData):Promise<SalesState>{const p=activitySchema.safeParse(Object.fromEntries(fd));if(!p.success)return{error:"Aktivite notunu girin."};const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return{error:"Oturum bulunamadı."};const{error}=await s.from("lead_activities").insert({...p.data,created_by:user.id});if(error)return{error:error.message};revalidatePath(`/sales/${p.data.lead_id}`);return{success:"Aktivite eklendi."}}
export async function convertLead(leadId:string,clientType:"direct"|"agency"|"partner"|"other"){const s=await createClient();const{data,error}=await s.rpc("convert_lead_to_client",{p_lead_id:leadId,p_client_type:clientType});if(error)throw new Error(error.message);revalidatePath("/sales");revalidatePath("/clients");return String(data)}
