create type public.proforma_status as enum('draft','sent','paid','cancelled');create sequence public.proforma_number_seq start 1;
create table public.proformas(id uuid primary key default gen_random_uuid(),proforma_number text not null unique,offer_id uuid references public.offers(id),offer_revision_id uuid references public.offer_revisions(id),client_id uuid not null references public.clients(id),issue_date date not null,valid_until date,currency public.currency_code not null,status public.proforma_status not null default'draft',bank_details text,description text,payment_terms text,subtotal numeric(18,2)not null,total_discount numeric(18,2)not null,total_vat numeric(18,2)not null,grand_total numeric(18,2)not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.proforma_items(id uuid primary key default gen_random_uuid(),proforma_id uuid not null references public.proformas(id)on delete restrict,service_name text,description text not null,quantity numeric(12,2)not null,unit_price numeric(18,2)not null,discount_rate numeric(5,2)not null,vat_rate numeric(5,2)not null,line_net numeric(18,2)not null,line_vat numeric(18,2)not null,line_total numeric(18,2)not null,position integer not null);
create index proformas_client_idx on public.proformas(client_id);create index proformas_status_idx on public.proformas(status);create index proforma_items_parent_idx on public.proforma_items(proforma_id,position);
alter table public.proformas enable row level security;alter table public.proforma_items enable row level security;create policy proformas_read on public.proformas for select to authenticated using(public.has_permission('sales.read'));create policy proformas_manage on public.proformas for all to authenticated using(public.has_permission('sales.manage'))with check(public.has_permission('sales.manage'));create policy proforma_items_read on public.proforma_items for select to authenticated using(public.has_permission('sales.read'));create policy proforma_items_insert on public.proforma_items for insert to authenticated with check(public.has_permission('sales.manage'));
create or replace function public.create_proforma_from_offer(p_offer_id uuid,p_issue_date date,p_valid_until date,p_bank_details text)returns uuid language plpgsql security invoker set search_path=''as $$
declare source_offer public.offers%rowtype;source_revision public.offer_revisions%rowtype;new_id uuid;
begin if not public.has_permission('sales.manage')then raise exception'insufficient_permission'using errcode='42501';end if;select*into source_offer from public.offers where id=p_offer_id;if source_offer.client_id is null then raise exception'offer_must_belong_to_client';end if;select*into source_revision from public.offer_revisions where offer_id=p_offer_id and revision_number=source_offer.current_revision;
insert into public.proformas(proforma_number,offer_id,offer_revision_id,client_id,issue_date,valid_until,currency,bank_details,description,payment_terms,subtotal,total_discount,total_vat,grand_total,created_by)values('PRF-'||extract(year from p_issue_date)::int||'-'||lpad(nextval('public.proforma_number_seq')::text,4,'0'),p_offer_id,source_revision.id,source_offer.client_id,p_issue_date,p_valid_until,source_offer.currency,p_bank_details,source_revision.description,source_revision.payment_terms,source_revision.subtotal,source_revision.total_discount,source_revision.total_vat,source_revision.grand_total,auth.uid())returning id into new_id;
insert into public.proforma_items(proforma_id,service_name,description,quantity,unit_price,discount_rate,vat_rate,line_net,line_vat,line_total,position)select new_id,s.name,i.description,i.quantity,i.unit_price,i.discount_rate,i.vat_rate,i.line_net,i.line_vat,i.line_total,i.position from public.offer_revision_items i left join public.services s on s.id=i.service_id where i.revision_id=source_revision.id;return new_id;end$$;
grant execute on function public.create_proforma_from_offer(uuid,date,date,text)to authenticated;
