create type public.task_status as enum ('todo','in_progress','waiting_client','review','completed');
create type public.task_priority as enum ('low','normal','high','urgent');
create type public.waiting_reason as enum ('client','internal_team','freelancer','materials','technical','other');
create type public.recurrence_type as enum ('daily','weekly','monthly','custom');
create type public.report_status as enum ('planned','preparing','ready','sent','approved');

create table public.tasks(
 id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id), project_service_id uuid references public.project_services(id),
 title text not null, description text, priority public.task_priority not null default 'normal', status public.task_status not null default 'todo',
 waiting_reason public.waiting_reason, start_date date, due_date date, completed_at timestamptz, created_by uuid not null references public.profiles(id), updated_by uuid references public.profiles(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(due_date is null or start_date is null or due_date>=start_date)
);
create table public.task_assignees(task_id uuid not null references public.tasks(id) on delete cascade,profile_id uuid not null references public.profiles(id),assigned_at timestamptz not null default now(),primary key(task_id,profile_id));
create table public.task_comments(id uuid primary key default gen_random_uuid(),task_id uuid not null references public.tasks(id) on delete cascade,body text not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.task_checklists(id uuid primary key default gen_random_uuid(),task_id uuid not null references public.tasks(id) on delete cascade,title text not null,is_completed boolean not null default false,position integer not null default 0,completed_by uuid references public.profiles(id),completed_at timestamptz,created_at timestamptz not null default now());
create table public.recurring_task_templates(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id),project_service_id uuid references public.project_services(id),title text not null,description text,priority public.task_priority not null default 'normal',recurrence public.recurrence_type not null,interval_value integer not null default 1 check(interval_value>0),custom_rule jsonb,starts_on date not null,next_run_on date not null,ends_on date,is_active boolean not null default true,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.reports(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id),project_service_id uuid references public.project_services(id),period date not null,title text not null,file_path text,url text,prepared_by uuid references public.profiles(id),status public.report_status not null default 'planned',sent_at timestamptz,client_feedback text,notes text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.activity_logs(id uuid primary key default gen_random_uuid(),actor_id uuid references public.profiles(id),entity_type text not null,entity_id uuid not null,action text not null,old_values jsonb,new_values jsonb,metadata jsonb,created_at timestamptz not null default now());

create index tasks_project_status_idx on public.tasks(project_id,status);create index tasks_due_date_idx on public.tasks(due_date) where status<>'completed';create index task_assignees_profile_idx on public.task_assignees(profile_id);create index reports_project_period_idx on public.reports(project_id,period);create index reports_status_idx on public.reports(status);create index recurring_next_run_idx on public.recurring_task_templates(next_run_on) where is_active;create index activity_entity_idx on public.activity_logs(entity_type,entity_id,created_at desc);
create trigger set_updated_at before update on public.tasks for each row execute function public.set_updated_at();create trigger set_updated_at before update on public.task_comments for each row execute function public.set_updated_at();create trigger set_updated_at before update on public.recurring_task_templates for each row execute function public.set_updated_at();create trigger set_updated_at before update on public.reports for each row execute function public.set_updated_at();

create or replace function public.log_task_change() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.activity_logs(actor_id,entity_type,entity_id,action,old_values,new_values) values(auth.uid(),'task',new.id,case when tg_op='INSERT' then 'created' else 'updated' end,case when tg_op='UPDATE' then to_jsonb(old) else null end,to_jsonb(new));return new;end $$;
create trigger task_activity after insert or update on public.tasks for each row execute function public.log_task_change();

insert into public.permissions(key,name,module) values('operations.read','Operasyon kayıtlarını görüntüle','operations'),('operations.manage','Görev ve raporları yönet','operations');
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r cross join public.permissions p where r.slug='super-admin' and p.module='operations';
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.key in('operations.read','operations.manage') where r.slug in('partner','employee');

alter table public.tasks enable row level security;alter table public.task_assignees enable row level security;alter table public.task_comments enable row level security;alter table public.task_checklists enable row level security;alter table public.recurring_task_templates enable row level security;alter table public.reports enable row level security;alter table public.activity_logs enable row level security;
create policy tasks_read on public.tasks for select to authenticated using(public.can_access_project(project_id) and public.has_permission('operations.read'));
create policy tasks_manage on public.tasks for all to authenticated using(public.can_access_project(project_id) and public.has_permission('operations.manage')) with check(public.can_access_project(project_id) and public.has_permission('operations.manage'));
create policy task_assignees_access on public.task_assignees for all to authenticated using(exists(select 1 from public.tasks t where t.id=task_id and public.can_access_project(t.project_id)) and public.has_permission('operations.read')) with check(exists(select 1 from public.tasks t where t.id=task_id and public.can_access_project(t.project_id)) and public.has_permission('operations.manage'));
create policy task_comments_access on public.task_comments for all to authenticated using(exists(select 1 from public.tasks t where t.id=task_id and public.can_access_project(t.project_id)) and public.has_permission('operations.read')) with check(exists(select 1 from public.tasks t where t.id=task_id and public.can_access_project(t.project_id)) and public.has_permission('operations.manage'));
create policy task_checklists_access on public.task_checklists for all to authenticated using(exists(select 1 from public.tasks t where t.id=task_id and public.can_access_project(t.project_id)) and public.has_permission('operations.read')) with check(exists(select 1 from public.tasks t where t.id=task_id and public.can_access_project(t.project_id)) and public.has_permission('operations.manage'));
create policy recurring_access on public.recurring_task_templates for all to authenticated using(public.can_access_project(project_id) and public.has_permission('operations.read')) with check(public.can_access_project(project_id) and public.has_permission('operations.manage'));
create policy reports_access on public.reports for all to authenticated using(public.can_access_project(project_id) and public.has_permission('operations.read')) with check(public.can_access_project(project_id) and public.has_permission('operations.manage'));
create policy activity_read on public.activity_logs for select to authenticated using(public.has_permission('settings.manage') or(actor_id=auth.uid()));
