create or replace function public.generate_service_periods(p_year integer,p_month integer)returns integer language plpgsql security invoker set search_path=''as $$declare ps record;price record;period_start date:=make_date(p_year,p_month,1);period_end date:=(make_date(p_year,p_month,1)+interval'1 month - 1 day')::date;new_period uuid;count_created integer:=0;begin if not public.has_permission('finance.manage')then raise exception'insufficient_permission'using errcode='42501';end if;for ps in select x.*,p.client_id from public.project_services x join public.projects p on p.id=x.project_id where x.status='active'and x.periodicity in('monthly','variable_monthly')and x.start_date<=period_end and(x.end_date is null or x.end_date>=period_start)loop select*into price from public.project_service_prices where project_service_id=ps.id and effective_from<=period_start and(effective_to is null or effective_to>=period_start)order by effective_from desc limit 1;if price.id is not null then insert into public.service_periods(project_service_id,client_id,project_id,service_id,year,month,net_amount,vat_rate,vat_amount,gross_amount,currency,billing_preference,due_date,notes,created_by)values(ps.id,ps.client_id,ps.project_id,ps.service_id,p_year,p_month,price.net_price,price.vat_rate,round(price.net_price*price.vat_rate/100,2),round(price.net_price*(1+price.vat_rate/100),2),price.currency,ps.billing_preference,period_end+ps.payment_term_days,case when ps.periodicity='variable_monthly'then'Bu aya ait iş ve tutar kontrol edilmeli.'else null end,auth.uid())on conflict(project_service_id,year,month)do nothing returning id into new_period;if new_period is not null then insert into public.receivables(service_period_id,client_id,project_id,total_amount,currency,due_date,created_by)select id,client_id,project_id,gross_amount,currency,due_date,auth.uid()from public.service_periods where id=new_period;count_created:=count_created+1;new_period:=null;end if;end if;end loop;return count_created;end$$;

create or replace function public.update_variable_service_period(p_service_period_id uuid,p_net_amount numeric,p_notes text)returns void language plpgsql security definer set search_path=''as $$declare period public.service_periods%rowtype;periodicity public.service_periodicity;new_vat numeric;new_gross numeric;already_paid numeric;begin if not public.has_permission('finance.manage')then raise exception'insufficient_permission'using errcode='42501';end if;select*into period from public.service_periods where id=p_service_period_id for update;if not found then raise exception'service_period_not_found';end if;select ps.periodicity into periodicity from public.project_services ps where ps.id=period.project_service_id;if periodicity<>'variable_monthly'then raise exception'not_variable_monthly';end if;if p_net_amount<0 then raise exception'invalid_amount';end if;new_vat:=round(p_net_amount*period.vat_rate/100,2);new_gross:=p_net_amount+new_vat;select coalesce(sum(p.amount),0)into already_paid from public.payments p join public.receivables r on r.id=p.receivable_id where r.service_period_id=period.id;if already_paid>new_gross then raise exception'payments_exceed_new_total';end if;update public.service_periods set net_amount=p_net_amount,vat_amount=new_vat,gross_amount=new_gross,notes=nullif(trim(p_notes),'')where id=period.id;update public.receivables set total_amount=new_gross,status=case when already_paid>=new_gross and new_gross>0 then'paid'::public.collection_status when already_paid>0 then'partial'::public.collection_status else'pending'::public.collection_status end where service_period_id=period.id;end$$;

grant execute on function public.generate_service_periods(integer,integer)to authenticated;
revoke all on function public.update_variable_service_period(uuid,numeric,text)from public;
grant execute on function public.update_variable_service_period(uuid,numeric,text)to authenticated;

update public.project_services ps set periodicity='variable_monthly',updated_at=now() from public.projects p,public.services s where ps.project_id=p.id and ps.service_id=s.id and lower(p.domain)='teramedya.com.tr' and lower(s.name)='komisyon' and ps.status='active';

with candidates as(select ps.id project_service_id,p.client_id,ps.project_id,ps.service_id,extract(year from current_date)::integer period_year,extract(month from current_date)::integer period_month,price.net_price,price.vat_rate,price.currency,ps.billing_preference,(date_trunc('month',current_date)+interval'1 month - 1 day')::date+ps.payment_term_days due_date,ps.created_by from public.project_services ps join public.projects p on p.id=ps.project_id join lateral(select*from public.project_service_prices x where x.project_service_id=ps.id and x.effective_from<=current_date and(x.effective_to is null or x.effective_to>=current_date)order by x.effective_from desc limit 1)price on true where ps.periodicity='variable_monthly'and ps.status='active'),inserted as(insert into public.service_periods(project_service_id,client_id,project_id,service_id,year,month,net_amount,vat_rate,vat_amount,gross_amount,currency,billing_preference,due_date,notes,created_by)select project_service_id,client_id,project_id,service_id,period_year,period_month,net_price,vat_rate,round(net_price*vat_rate/100,2),round(net_price*(1+vat_rate/100),2),currency,billing_preference,due_date,'Bu aya ait iş ve tutar kontrol edilmeli.',created_by from candidates on conflict(project_service_id,year,month)do nothing returning*)insert into public.receivables(service_period_id,client_id,project_id,total_amount,currency,due_date,created_by)select id,client_id,project_id,gross_amount,currency,due_date,created_by from inserted on conflict(service_period_id)do nothing;
