alter table public.offer_revision_items
  add column if not exists custom_service_name text;

create or replace function public.create_offer_with_revision(p_client_id uuid,p_lead_id uuid,p_offer_date date,p_valid_until date,p_sales_owner_id uuid,p_currency public.currency_code,p_description text,p_payment_terms text,p_notes text,p_items jsonb)returns uuid language plpgsql security invoker set search_path=''as $$
declare new_offer uuid;new_revision uuid;item jsonb;sub numeric:=0;discount numeric:=0;vat numeric:=0;line_base numeric;line_discount numeric;line_net_value numeric;line_vat_value numeric;grand numeric:=0;pos integer:=0;
begin
 if not public.has_permission('sales.manage')then raise exception'insufficient_permission'using errcode='42501';end if;if jsonb_array_length(p_items)=0 then raise exception'offer_requires_items';end if;
 for item in select*from jsonb_array_elements(p_items)loop line_base:=round(((item->>'quantity')::numeric)*((item->>'unit_price')::numeric),2);line_discount:=round(line_base*coalesce((item->>'discount_rate')::numeric,0)/100,2);line_net_value:=line_base-line_discount;line_vat_value:=round(line_net_value*coalesce((item->>'vat_rate')::numeric,0)/100,2);sub:=sub+line_base;discount:=discount+line_discount;vat:=vat+line_vat_value;grand:=grand+line_net_value+line_vat_value;end loop;
 insert into public.offers(offer_number,client_id,lead_id,offer_date,valid_until,sales_owner_id,currency,created_by,updated_by)values('WL-'||extract(year from p_offer_date)::int||'-'||lpad(nextval('public.offer_number_seq')::text,4,'0'),p_client_id,p_lead_id,p_offer_date,p_valid_until,p_sales_owner_id,p_currency,auth.uid(),auth.uid())returning id into new_offer;
 insert into public.offer_revisions(offer_id,revision_number,description,payment_terms,notes,subtotal,total_discount,total_vat,grand_total,created_by)values(new_offer,1,p_description,p_payment_terms,p_notes,sub,discount,vat,grand,auth.uid())returning id into new_revision;
 for item in select*from jsonb_array_elements(p_items)loop line_base:=round(((item->>'quantity')::numeric)*((item->>'unit_price')::numeric),2);line_discount:=round(line_base*coalesce((item->>'discount_rate')::numeric,0)/100,2);line_net_value:=line_base-line_discount;line_vat_value:=round(line_net_value*coalesce((item->>'vat_rate')::numeric,0)/100,2);insert into public.offer_revision_items(revision_id,service_id,custom_service_name,description,quantity,unit_price,discount_rate,vat_rate,line_net,line_vat,line_total,position)values(new_revision,nullif(item->>'service_id','')::uuid,nullif(trim(item->>'custom_service_name'),''),item->>'description',(item->>'quantity')::numeric,(item->>'unit_price')::numeric,coalesce((item->>'discount_rate')::numeric,0),coalesce((item->>'vat_rate')::numeric,0),line_net_value,line_vat_value,line_net_value+line_vat_value,pos);pos:=pos+1;end loop;return new_offer;
end$$;

create or replace function public.create_offer_revision(p_offer_id uuid,p_description text,p_payment_terms text,p_notes text,p_items jsonb)returns integer language plpgsql security invoker set search_path=''as $$
declare new_revision_id uuid;next_revision integer;item jsonb;sub numeric:=0;discount numeric:=0;vat numeric:=0;line_base numeric;line_discount numeric;line_net_value numeric;line_vat_value numeric;grand numeric:=0;pos integer:=0;
begin
 if not public.has_permission('sales.manage')then raise exception'insufficient_permission'using errcode='42501';end if;if jsonb_array_length(p_items)=0 then raise exception'offer_requires_items';end if;
 select current_revision+1 into next_revision from public.offers where id=p_offer_id for update;if next_revision is null then raise exception'offer_not_found';end if;
 for item in select*from jsonb_array_elements(p_items)loop line_base:=round((item->>'quantity')::numeric*(item->>'unit_price')::numeric,2);line_discount:=round(line_base*coalesce((item->>'discount_rate')::numeric,0)/100,2);line_net_value:=line_base-line_discount;line_vat_value:=round(line_net_value*coalesce((item->>'vat_rate')::numeric,0)/100,2);sub:=sub+line_base;discount:=discount+line_discount;vat:=vat+line_vat_value;grand:=grand+line_net_value+line_vat_value;end loop;
 insert into public.offer_revisions(offer_id,revision_number,description,payment_terms,notes,subtotal,total_discount,total_vat,grand_total,created_by)values(p_offer_id,next_revision,p_description,p_payment_terms,p_notes,sub,discount,vat,grand,auth.uid())returning id into new_revision_id;
 for item in select*from jsonb_array_elements(p_items)loop line_base:=round((item->>'quantity')::numeric*(item->>'unit_price')::numeric,2);line_discount:=round(line_base*coalesce((item->>'discount_rate')::numeric,0)/100,2);line_net_value:=line_base-line_discount;line_vat_value:=round(line_net_value*coalesce((item->>'vat_rate')::numeric,0)/100,2);insert into public.offer_revision_items(revision_id,service_id,custom_service_name,description,quantity,unit_price,discount_rate,vat_rate,line_net,line_vat,line_total,position)values(new_revision_id,nullif(item->>'service_id','')::uuid,nullif(trim(item->>'custom_service_name'),''),item->>'description',(item->>'quantity')::numeric,(item->>'unit_price')::numeric,coalesce((item->>'discount_rate')::numeric,0),coalesce((item->>'vat_rate')::numeric,0),line_net_value,line_vat_value,line_net_value+line_vat_value,pos);pos:=pos+1;end loop;
 update public.offers set current_revision=next_revision,status='revising',updated_by=auth.uid()where id=p_offer_id;return next_revision;
end$$;

create or replace function public.create_proforma_from_offer(p_offer_id uuid,p_issue_date date,p_valid_until date,p_bank_details text)returns uuid language plpgsql security invoker set search_path=''as $$
declare source_offer public.offers%rowtype;source_revision public.offer_revisions%rowtype;new_id uuid;
begin if not public.has_permission('sales.manage')then raise exception'insufficient_permission'using errcode='42501';end if;select*into source_offer from public.offers where id=p_offer_id;if source_offer.client_id is null then raise exception'offer_must_belong_to_client';end if;select*into source_revision from public.offer_revisions where offer_id=p_offer_id and revision_number=source_offer.current_revision;
insert into public.proformas(proforma_number,offer_id,offer_revision_id,client_id,issue_date,valid_until,currency,bank_details,description,payment_terms,subtotal,total_discount,total_vat,grand_total,created_by)values('PRF-'||extract(year from p_issue_date)::int||'-'||lpad(nextval('public.proforma_number_seq')::text,4,'0'),p_offer_id,source_revision.id,source_offer.client_id,p_issue_date,p_valid_until,source_offer.currency,p_bank_details,source_revision.description,source_revision.payment_terms,source_revision.subtotal,source_revision.total_discount,source_revision.total_vat,source_revision.grand_total,auth.uid())returning id into new_id;
insert into public.proforma_items(proforma_id,service_name,description,quantity,unit_price,discount_rate,vat_rate,line_net,line_vat,line_total,position)select new_id,coalesce(i.custom_service_name,s.name),i.description,i.quantity,i.unit_price,i.discount_rate,i.vat_rate,i.line_net,i.line_vat,i.line_total,i.position from public.offer_revision_items i left join public.services s on s.id=i.service_id where i.revision_id=source_revision.id;return new_id;end$$;
