create type public.vendor_type as enum ('freelancer','agency','company','developer','designer','content_creator','other');
create type public.accrual_status as enum ('pending','partial','paid','cancelled');
create type public.account_type as enum ('bank','cash','virtual','credit_card','other');
create type public.transaction_type as enum ('income','expense','transfer');

create table public.vendors(
 id uuid primary key default gen_random_uuid(),name text not null,vendor_type public.vendor_type not null default 'other',linked_profile_id uuid references public.profiles(id),phone text,email text,tax_office text,tax_number text,bank_details text,status public.record_status not null default 'active',notes text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.vendor_assignments(
 id uuid primary key default gen_random_uuid(),vendor_id uuid not null references public.vendors(id),project_service_id uuid not null references public.project_services(id),start_date date not null,end_date date,default_amount numeric(18,2) not null default 0 check(default_amount>=0),currency public.currency_code not null default 'TRY',status public.record_status not null default 'active',notes text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date is null or end_date>=start_date),unique(vendor_id,project_service_id,start_date)
);
create table public.vendor_accruals(
 id uuid primary key default gen_random_uuid(),vendor_id uuid not null references public.vendors(id),vendor_assignment_id uuid references public.vendor_assignments(id),project_id uuid not null references public.projects(id),project_service_id uuid not null references public.project_services(id),year integer not null check(year between 2000 and 2200),month integer not null check(month between 1 and 12),amount numeric(18,2) not null check(amount>=0),currency public.currency_code not null,due_date date,status public.accrual_status not null default 'pending',notes text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(vendor_assignment_id,year,month)
);
create table public.accounts(
 id uuid primary key default gen_random_uuid(),name text not null unique,account_type public.account_type not null,currency public.currency_code not null default 'TRY',billing_preference public.billing_preference not null default 'invoiced',opening_balance numeric(18,2) not null default 0,status public.record_status not null default 'active',notes text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.finance_transactions(
 id uuid primary key default gen_random_uuid(),account_id uuid not null references public.accounts(id),transaction_date date not null,transaction_type public.transaction_type not null,amount numeric(18,2) not null check(amount<>0),currency public.currency_code not null,client_id uuid references public.clients(id),project_id uuid references public.projects(id),service_id uuid references public.services(id),vendor_id uuid references public.vendors(id),category text,description text,document_path text,transfer_group_id uuid,payment_id uuid references public.payments(id),created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),check((transaction_type='income' and amount>0)or(transaction_type='expense' and amount<0)or transaction_type='transfer')
);
create table public.vendor_payments(
 id uuid primary key default gen_random_uuid(),vendor_accrual_id uuid not null references public.vendor_accruals(id),account_id uuid not null references public.accounts(id),amount numeric(18,2) not null check(amount>0),currency public.currency_code not null,payment_date date not null,transaction_id uuid unique references public.finance_transactions(id),notes text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now()
);
alter table public.payments add constraint payments_account_id_fkey foreign key(account_id) references public.accounts(id);

create index vendor_assignments_service_idx on public.vendor_assignments(project_service_id,status);
create index vendor_accruals_period_idx on public.vendor_accruals(year,month,status);
create index finance_transactions_account_date_idx on public.finance_transactions(account_id,transaction_date desc);
create index vendor_payments_accrual_idx on public.vendor_payments(vendor_accrual_id,payment_date);
create trigger set_updated_at before update on public.vendors for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.vendor_assignments for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.vendor_accruals for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.accounts for each row execute function public.set_updated_at();

insert into public.permissions(key,name,module)values('vendors.read','Tedarikçileri görüntüle','vendors'),('vendors.manage','Tedarikçileri yönet','vendors'),('accounts.read','Kasa ve hareketleri görüntüle','accounts'),('accounts.manage','Kasa ve hareketleri yönet','accounts')on conflict(key)do nothing;
insert into public.role_permissions(role_id,permission_id)select r.id,p.id from public.roles r cross join public.permissions p where r.slug='super-admin'and p.module in('vendors','accounts')on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)select r.id,p.id from public.roles r cross join public.permissions p where r.slug in('partner','accounting')and p.key in('vendors.read','vendors.manage','accounts.read','accounts.manage')on conflict do nothing;

alter table public.vendors enable row level security;alter table public.vendor_assignments enable row level security;alter table public.vendor_accruals enable row level security;alter table public.accounts enable row level security;alter table public.finance_transactions enable row level security;alter table public.vendor_payments enable row level security;
create policy vendors_read on public.vendors for select to authenticated using(public.has_permission('vendors.read'));
create policy vendors_manage on public.vendors for all to authenticated using(public.has_permission('vendors.manage'))with check(public.has_permission('vendors.manage'));
create policy vendor_assignments_read on public.vendor_assignments for select to authenticated using(public.has_permission('vendors.read'));
create policy vendor_assignments_manage on public.vendor_assignments for all to authenticated using(public.has_permission('vendors.manage'))with check(public.has_permission('vendors.manage'));
create policy vendor_accruals_read on public.vendor_accruals for select to authenticated using(public.has_permission('vendors.read')or public.has_permission('finance.read'));
create policy vendor_accruals_manage on public.vendor_accruals for all to authenticated using(public.has_permission('vendors.manage'))with check(public.has_permission('vendors.manage'));
create policy accounts_read on public.accounts for select to authenticated using(public.has_permission('accounts.read'));
create policy accounts_manage on public.accounts for all to authenticated using(public.has_permission('accounts.manage'))with check(public.has_permission('accounts.manage'));
create policy transactions_read on public.finance_transactions for select to authenticated using(public.has_permission('accounts.read'));
create policy transactions_insert on public.finance_transactions for insert to authenticated with check(public.has_permission('accounts.manage')and created_by=auth.uid());
create policy vendor_payments_read on public.vendor_payments for select to authenticated using(public.has_permission('vendors.read')or public.has_permission('accounts.read'));
create policy vendor_payments_insert on public.vendor_payments for insert to authenticated with check((public.has_permission('vendors.manage')or public.has_permission('accounts.manage'))and created_by=auth.uid());

create or replace function public.generate_vendor_accruals(p_year integer,p_month integer)returns integer language plpgsql security invoker set search_path=''as $$declare a record;period_start date:=make_date(p_year,p_month,1);period_end date:=(make_date(p_year,p_month,1)+interval'1 month - 1 day')::date;created_count integer:=0;begin if not public.has_permission('vendors.manage')then raise exception'insufficient_permission'using errcode='42501';end if;for a in select va.*,ps.project_id from public.vendor_assignments va join public.project_services ps on ps.id=va.project_service_id where va.status='active'and va.start_date<=period_end and(va.end_date is null or va.end_date>=period_start)loop insert into public.vendor_accruals(vendor_id,vendor_assignment_id,project_id,project_service_id,year,month,amount,currency,due_date,created_by)values(a.vendor_id,a.id,a.project_id,a.project_service_id,p_year,p_month,a.default_amount,a.currency,period_end,auth.uid())on conflict(vendor_assignment_id,year,month)do nothing;if found then created_count:=created_count+1;end if;end loop;return created_count;end$$;

create or replace function public.transfer_between_accounts(p_source uuid,p_target uuid,p_amount numeric,p_date date,p_description text)returns uuid language plpgsql security invoker set search_path=''as $$declare source_currency public.currency_code;target_currency public.currency_code;group_id uuid:=gen_random_uuid();begin if not public.has_permission('accounts.manage')then raise exception'insufficient_permission'using errcode='42501';end if;if p_source=p_target or p_amount<=0 then raise exception'invalid_transfer';end if;select currency into source_currency from public.accounts where id=p_source and status='active';select currency into target_currency from public.accounts where id=p_target and status='active';if source_currency is null or target_currency is null or source_currency<>target_currency then raise exception'currency_mismatch_or_account_missing';end if;insert into public.finance_transactions(account_id,transaction_date,transaction_type,amount,currency,category,description,transfer_group_id,created_by)values(p_source,p_date,'transfer',-p_amount,source_currency,'Kasa transferi',p_description,group_id,auth.uid()),(p_target,p_date,'transfer',p_amount,target_currency,'Kasa transferi',p_description,group_id,auth.uid());return group_id;end$$;

create or replace function public.pay_vendor_accrual(p_accrual_id uuid,p_account_id uuid,p_amount numeric,p_payment_date date,p_notes text)returns uuid language plpgsql security invoker set search_path=''as $$declare accrual public.vendor_accruals%rowtype;account_currency public.currency_code;paid numeric;tx_id uuid;payment_id uuid;new_status public.accrual_status;begin if not(public.has_permission('vendors.manage')and public.has_permission('accounts.manage'))then raise exception'insufficient_permission'using errcode='42501';end if;select*into accrual from public.vendor_accruals where id=p_accrual_id for update;if not found then raise exception'accrual_not_found';end if;select currency into account_currency from public.accounts where id=p_account_id and status='active';if account_currency is null or account_currency<>accrual.currency then raise exception'currency_mismatch_or_account_missing';end if;select coalesce(sum(amount),0)into paid from public.vendor_payments where vendor_accrual_id=p_accrual_id;if p_amount<=0 or paid+p_amount>accrual.amount then raise exception'invalid_payment_amount';end if;insert into public.finance_transactions(account_id,transaction_date,transaction_type,amount,currency,project_id,vendor_id,category,description,created_by)values(p_account_id,p_payment_date,'expense',-p_amount,accrual.currency,accrual.project_id,accrual.vendor_id,'Tedarikçi ödemesi',p_notes,auth.uid())returning id into tx_id;insert into public.vendor_payments(vendor_accrual_id,account_id,amount,currency,payment_date,transaction_id,notes,created_by)values(p_accrual_id,p_account_id,p_amount,accrual.currency,p_payment_date,tx_id,p_notes,auth.uid())returning id into payment_id;paid:=paid+p_amount;new_status:=case when paid>=accrual.amount then'paid'::public.accrual_status else'partial'::public.accrual_status end;update public.vendor_accruals set status=new_status where id=p_accrual_id;return payment_id;end$$;

create or replace function public.account_balances()returns table(account_id uuid,balance numeric)language sql stable security invoker set search_path=''as $$select a.id,a.opening_balance+coalesce(sum(t.amount),0)from public.accounts a left join public.finance_transactions t on t.account_id=a.id where public.has_permission('accounts.read')group by a.id,a.opening_balance$$;
grant execute on function public.generate_vendor_accruals(integer,integer)to authenticated;
grant execute on function public.transfer_between_accounts(uuid,uuid,numeric,date,text)to authenticated;
grant execute on function public.pay_vendor_accrual(uuid,uuid,numeric,date,text)to authenticated;
grant execute on function public.account_balances()to authenticated;

insert into public.accounts(name,account_type,currency,billing_preference,opening_balance,created_by)
select seed.name,seed.account_type::public.account_type,'TRY'::public.currency_code,seed.billing::public.billing_preference,0,p.id from(values('Şirket Tahsilat Kasası','bank','invoiced'),('Şirket Gider Kasası','bank','invoiced'),('Faturasız Tahsilat Kasası','bank','uninvoiced'),('Faturasız Gider Kasası','bank','uninvoiced'))seed(name,account_type,billing)cross join lateral(select id from public.profiles order by created_at limit 1)p on conflict(name)do nothing;
