create type public.offer_status as enum('draft','ready','sent','revising','accepted','rejected','expired');
create sequence public.offer_number_seq start 1;
create table public.offers(id uuid primary key default gen_random_uuid(),offer_number text not null unique,client_id uuid references public.clients(id),lead_id uuid references public.leads(id),offer_date date not null,valid_until date,sales_owner_id uuid references public.profiles(id),currency public.currency_code not null default'TRY',status public.offer_status not null default'draft',current_revision integer not null default 1,created_by uuid not null references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check((client_id is not null)::int+(lead_id is not null)::int=1));
create table public.offer_revisions(id uuid primary key default gen_random_uuid(),offer_id uuid not null references public.offers(id),revision_number integer not null,description text,payment_terms text,notes text,subtotal numeric(18,2)not null,total_discount numeric(18,2)not null,total_vat numeric(18,2)not null,grand_total numeric(18,2)not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(offer_id,revision_number));
create table public.offer_revision_items(id uuid primary key default gen_random_uuid(),revision_id uuid not null references public.offer_revisions(id)on delete restrict,service_id uuid references public.services(id),description text not null,quantity numeric(12,2)not null check(quantity>0),unit_price numeric(18,2)not null check(unit_price>=0),discount_rate numeric(5,2)not null default 0 check(discount_rate between 0 and 100),vat_rate numeric(5,2)not null default 20 check(vat_rate between 0 and 100),line_net numeric(18,2)not null,line_vat numeric(18,2)not null,line_total numeric(18,2)not null,position integer not null default 0);
create index offers_client_idx on public.offers(client_id);create index offers_lead_idx on public.offers(lead_id);create index offers_status_idx on public.offers(status);create index revisions_offer_idx on public.offer_revisions(offer_id,revision_number desc);create trigger set_updated_at before update on public.offers for each row execute function public.set_updated_at();
alter table public.offers enable row level security;alter table public.offer_revisions enable row level security;alter table public.offer_revision_items enable row level security;
create policy offers_read on public.offers for select to authenticated using(public.has_permission('sales.read'));create policy offers_manage on public.offers for all to authenticated using(public.has_permission('sales.manage'))with check(public.has_permission('sales.manage'));
create policy revisions_read on public.offer_revisions for select to authenticated using(public.has_permission('sales.read'));create policy revisions_insert on public.offer_revisions for insert to authenticated with check(public.has_permission('sales.manage')and created_by=auth.uid());
create policy revision_items_read on public.offer_revision_items for select to authenticated using(public.has_permission('sales.read'));create policy revision_items_insert on public.offer_revision_items for insert to authenticated with check(public.has_permission('sales.manage'));
create or replace function public.create_offer_with_revision(p_client_id uuid,p_lead_id uuid,p_offer_date date,p_valid_until date,p_sales_owner_id uuid,p_currency public.currency_code,p_description text,p_payment_terms text,p_notes text,p_items jsonb)returns uuid language plpgsql security invoker set search_path=''as $$
declare new_offer uuid;new_revision uuid;item jsonb;sub numeric:=0;discount numeric:=0;vat numeric:=0;line_base numeric;line_discount numeric;line_net_value numeric;line_vat_value numeric;grand numeric:=0;pos integer:=0;
begin
 if not public.has_permission('sales.manage')then raise exception'insufficient_permission'using errcode='42501';end if;if jsonb_array_length(p_items)=0 then raise exception'offer_requires_items';end if;
 for item in select*from jsonb_array_elements(p_items)loop line_base:=round(((item->>'quantity')::numeric)*((item->>'unit_price')::numeric),2);line_discount:=round(line_base*coalesce((item->>'discount_rate')::numeric,0)/100,2);line_net_value:=line_base-line_discount;line_vat_value:=round(line_net_value*coalesce((item->>'vat_rate')::numeric,0)/100,2);sub:=sub+line_base;discount:=discount+line_discount;vat:=vat+line_vat_value;grand:=grand+line_net_value+line_vat_value;end loop;
 insert into public.offers(offer_number,client_id,lead_id,offer_date,valid_until,sales_owner_id,currency,created_by,updated_by)values('WL-'||extract(year from p_offer_date)::int||'-'||lpad(nextval('public.offer_number_seq')::text,4,'0'),p_client_id,p_lead_id,p_offer_date,p_valid_until,p_sales_owner_id,p_currency,auth.uid(),auth.uid())returning id into new_offer;
 insert into public.offer_revisions(offer_id,revision_number,description,payment_terms,notes,subtotal,total_discount,total_vat,grand_total,created_by)values(new_offer,1,p_description,p_payment_terms,p_notes,sub,discount,vat,grand,auth.uid())returning id into new_revision;
 for item in select*from jsonb_array_elements(p_items)loop line_base:=round(((item->>'quantity')::numeric)*((item->>'unit_price')::numeric),2);line_discount:=round(line_base*coalesce((item->>'discount_rate')::numeric,0)/100,2);line_net_value:=line_base-line_discount;line_vat_value:=round(line_net_value*coalesce((item->>'vat_rate')::numeric,0)/100,2);insert into public.offer_revision_items(revision_id,service_id,description,quantity,unit_price,discount_rate,vat_rate,line_net,line_vat,line_total,position)values(new_revision,nullif(item->>'service_id','')::uuid,item->>'description',(item->>'quantity')::numeric,(item->>'unit_price')::numeric,coalesce((item->>'discount_rate')::numeric,0),coalesce((item->>'vat_rate')::numeric,0),line_net_value,line_vat_value,line_net_value+line_vat_value,pos);pos:=pos+1;end loop;return new_offer;
end$$;
grant execute on function public.create_offer_with_revision(uuid,uuid,date,date,uuid,public.currency_code,text,text,text,jsonb)to authenticated;
