create type public.notification_type as enum('task_due','task_overdue','report_due','receivable_overdue','vendor_payment_due','offer_expiring','system');
create table public.notifications(id uuid primary key default gen_random_uuid(),recipient_id uuid not null references public.profiles(id)on delete cascade,notification_type public.notification_type not null,title text not null,body text,href text,source_key text not null,is_read boolean not null default false,read_at timestamptz,created_at timestamptz not null default now(),unique(recipient_id,source_key));
create index notifications_recipient_idx on public.notifications(recipient_id,is_read,created_at desc);
alter table public.notifications enable row level security;
create policy notifications_read on public.notifications for select to authenticated using(recipient_id=auth.uid());
create policy notifications_update on public.notifications for update to authenticated using(recipient_id=auth.uid())with check(recipient_id=auth.uid());
create or replace function public.refresh_my_notifications()returns integer language plpgsql security invoker set search_path=''as $$declare created_count integer:=0;inserted_count integer:=0;begin
insert into public.notifications(recipient_id,notification_type,title,body,href,source_key)
select auth.uid(),case when t.due_date<current_date then'task_overdue'::public.notification_type else'task_due'::public.notification_type end,case when t.due_date<current_date then'Görev gecikti'else'Görev son tarihi yaklaşıyor'end,t.title||' · '||coalesce(p.name,''),'/projects/'||t.project_id||'/tasks/'||t.id,'task:'||t.id||':'||t.due_date from public.tasks t join public.task_assignees a on a.task_id=t.id join public.projects p on p.id=t.project_id where a.profile_id=auth.uid()and t.status<>'completed'and t.due_date<=current_date+2 on conflict(recipient_id,source_key)do nothing;get diagnostics created_count=row_count;
if public.has_permission('collections.read')or public.has_permission('finance.read')then insert into public.notifications(recipient_id,notification_type,title,body,href,source_key)select auth.uid(),'receivable_overdue','Gecikmiş müşteri ödemesi',c.company_name||' · '||r.total_amount||' '||r.currency,'/collections/'||r.id,'receivable:'||r.id||':'||r.due_date from public.receivables r join public.clients c on c.id=r.client_id where r.status<>'paid'and r.due_date<current_date on conflict(recipient_id,source_key)do nothing;get diagnostics inserted_count=row_count;created_count:=created_count+inserted_count;end if;
if public.has_permission('vendors.read')then insert into public.notifications(recipient_id,notification_type,title,body,href,source_key)select auth.uid(),'vendor_payment_due','Tedarikçi ödemesi yaklaşıyor',v.name||' · '||a.amount||' '||a.currency,'/vendor-payments','vendor-accrual:'||a.id||':'||a.due_date from public.vendor_accruals a join public.vendors v on v.id=a.vendor_id where a.status in('pending','partial')and a.due_date<=current_date+3 on conflict(recipient_id,source_key)do nothing;get diagnostics inserted_count=row_count;created_count:=created_count+inserted_count;end if;
if public.has_permission('sales.read')then insert into public.notifications(recipient_id,notification_type,title,body,href,source_key)select auth.uid(),'offer_expiring','Teklif süresi doluyor',o.offer_number||' · '||coalesce(c.company_name,l.company_name,''),'/offers/'||o.id,'offer:'||o.id||':'||o.valid_until from public.offers o left join public.clients c on c.id=o.client_id left join public.leads l on l.id=o.lead_id where o.status in('ready','sent','revising')and o.valid_until<=current_date+3 on conflict(recipient_id,source_key)do nothing;get diagnostics inserted_count=row_count;created_count:=created_count+inserted_count;end if;
return created_count;end$$;
create or replace function public.global_search(p_query text,p_limit integer default 8)returns table(category text,entity_id uuid,title text,subtitle text,href text)language plpgsql stable security invoker set search_path=''as $$declare pattern text:='%'||replace(replace(trim(p_query),'%','\%'),'_','\_')||'%';begin if length(trim(p_query))<2 then return;end if;return query
select*from(
select'Müşteri'::text,c.id,c.company_name,coalesce(c.short_name,c.email,''),'/clients/'||c.id from public.clients c where public.has_permission('clients.read')and c.status<>'archived'and(c.company_name ilike pattern escape'\'or coalesce(c.short_name,'')ilike pattern escape'\')
union all select'Proje',p.id,p.name,coalesce(p.domain,c.company_name),'/projects/'||p.id from public.projects p join public.clients c on c.id=p.client_id where public.can_access_project(p.id)and(p.name ilike pattern escape'\'or coalesce(p.domain,'')ilike pattern escape'\')
union all select'Lead',l.id,l.company_name,coalesce(l.contact_name,l.email,''),'/sales/'||l.id from public.leads l where public.has_permission('sales.read')and(l.company_name ilike pattern escape'\'or coalesce(l.contact_name,'')ilike pattern escape'\')
union all select'Teklif',o.id,o.offer_number,coalesce(c.company_name,l.company_name,''),'/offers/'||o.id from public.offers o left join public.clients c on c.id=o.client_id left join public.leads l on l.id=o.lead_id where public.has_permission('sales.read')and o.offer_number ilike pattern escape'\'
union all select'Proforma',p.id,p.proforma_number,c.company_name,'/proformas/'||p.id from public.proformas p join public.clients c on c.id=p.client_id where public.has_permission('sales.read')and p.proforma_number ilike pattern escape'\'
union all select'Görev',t.id,t.title,p.name,'/projects/'||t.project_id||'/tasks/'||t.id from public.tasks t join public.projects p on p.id=t.project_id where public.has_permission('operations.read')and public.can_access_project(t.project_id)and t.title ilike pattern escape'\'
union all select'Tedarikçi',v.id,v.name,coalesce(v.email,v.phone,''),'/vendors/'||v.id from public.vendors v where public.has_permission('vendors.read')and v.status<>'archived'and v.name ilike pattern escape'\'
)results limit greatest(1,least(p_limit,50));end$$;
grant execute on function public.refresh_my_notifications()to authenticated;grant execute on function public.global_search(text,integer)to authenticated;
