create or replace function public.create_offer_revision(p_offer_id uuid,p_description text,p_payment_terms text,p_notes text,p_items jsonb)returns integer language plpgsql security invoker set search_path=''as $$
declare new_revision_id uuid;next_revision integer;item jsonb;sub numeric:=0;discount numeric:=0;vat numeric:=0;line_base numeric;line_discount numeric;line_net_value numeric;line_vat_value numeric;grand numeric:=0;pos integer:=0;
begin
 if not public.has_permission('sales.manage')then raise exception'insufficient_permission'using errcode='42501';end if;if jsonb_array_length(p_items)=0 then raise exception'offer_requires_items';end if;
 select current_revision+1 into next_revision from public.offers where id=p_offer_id for update;if next_revision is null then raise exception'offer_not_found';end if;
 for item in select*from jsonb_array_elements(p_items)loop line_base:=round((item->>'quantity')::numeric*(item->>'unit_price')::numeric,2);line_discount:=round(line_base*coalesce((item->>'discount_rate')::numeric,0)/100,2);line_net_value:=line_base-line_discount;line_vat_value:=round(line_net_value*coalesce((item->>'vat_rate')::numeric,0)/100,2);sub:=sub+line_base;discount:=discount+line_discount;vat:=vat+line_vat_value;grand:=grand+line_net_value+line_vat_value;end loop;
 insert into public.offer_revisions(offer_id,revision_number,description,payment_terms,notes,subtotal,total_discount,total_vat,grand_total,created_by)values(p_offer_id,next_revision,p_description,p_payment_terms,p_notes,sub,discount,vat,grand,auth.uid())returning id into new_revision_id;
 for item in select*from jsonb_array_elements(p_items)loop line_base:=round((item->>'quantity')::numeric*(item->>'unit_price')::numeric,2);line_discount:=round(line_base*coalesce((item->>'discount_rate')::numeric,0)/100,2);line_net_value:=line_base-line_discount;line_vat_value:=round(line_net_value*coalesce((item->>'vat_rate')::numeric,0)/100,2);insert into public.offer_revision_items(revision_id,service_id,description,quantity,unit_price,discount_rate,vat_rate,line_net,line_vat,line_total,position)values(new_revision_id,nullif(item->>'service_id','')::uuid,item->>'description',(item->>'quantity')::numeric,(item->>'unit_price')::numeric,coalesce((item->>'discount_rate')::numeric,0),coalesce((item->>'vat_rate')::numeric,0),line_net_value,line_vat_value,line_net_value+line_vat_value,pos);pos:=pos+1;end loop;
 update public.offers set current_revision=next_revision,status='revising',updated_by=auth.uid()where id=p_offer_id;return next_revision;
end$$;
grant execute on function public.create_offer_revision(uuid,text,text,text,jsonb)to authenticated;
