"use client";
import{useState,useTransition}from"react";
import{setRolePermission}from"@/lib/actions/permissions";
type Role={id:string;name:string;slug:string};type Permission={id:string;key:string;name:string;module:string};
export function RolePermissionMatrix({roles,permissions,assignments}:{roles:Role[];permissions:Permission[];assignments:{role_id:string;permission_id:string}[]}){
  const[grants,setGrants]=useState(()=>new Set(assignments.map(x=>`${x.role_id}:${x.permission_id}`)));const[pending,start]=useTransition();const modules=[...new Set(permissions.map(x=>x.module))];
  function mutate(set:Set<string>,key:string,enabled:boolean){if(enabled)set.add(key);else set.delete(key)}
  function toggle(roleId:string,permissionId:string,enabled:boolean){const key=`${roleId}:${permissionId}`;setGrants(old=>{const next=new Set(old);mutate(next,key,enabled);return next});start(async()=>{try{await setRolePermission({role_id:roleId,permission_id:permissionId,enabled:String(enabled)as"true"|"false"})}catch{setGrants(old=>{const next=new Set(old);mutate(next,key,!enabled);return next})}})}
  return <div className="overflow-x-auto"><table className={`w-full min-w-[900px] text-sm ${pending?"opacity-70":""}`}><thead><tr className="border-b bg-slate-50"><th className="sticky left-0 bg-slate-50 px-4 py-3 text-left font-semibold">Yetki</th>{roles.map(r=><th key={r.id} className="px-3 py-3 text-center font-semibold">{r.name}</th>)}</tr></thead><tbody>{modules.map(module=><PermissionGroup key={module} module={module} roles={roles} permissions={permissions.filter(x=>x.module===module)} grants={grants} toggle={toggle}/>)}</tbody></table></div>
}
function PermissionGroup({module,roles,permissions,grants,toggle}:{module:string;roles:Role[];permissions:Permission[];grants:Set<string>;toggle:(r:string,p:string,e:boolean)=>void}){return <><tr><td colSpan={roles.length+1} className="bg-slate-100 px-4 py-2 text-xs font-bold uppercase tracking-wider text-slate-500">{module}</td></tr>{permissions.map(p=><tr key={p.id} className="border-b last:border-0"><td className="sticky left-0 bg-white px-4 py-3"><div className="font-medium">{p.name}</div><div className="text-xs text-slate-400">{p.key}</div></td>{roles.map(r=>{const checked=grants.has(`${r.id}:${p.id}`);return <td key={r.id} className="px-3 py-3 text-center"><input aria-label={`${r.name} ${p.name}`} type="checkbox" checked={checked} disabled={r.slug==="super-admin"} onChange={e=>toggle(r.id,p.id,e.target.checked)} className="h-4 w-4 accent-[#CD0B16]"/></td>})}</tr>)}</>}
